# web/src/main/resources/application.yml

spring:
  application:
    name: buskart-search-web
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081 # Example port; adjust as needed

# Swagger/OpenAPI Configuration (if using Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Security Configuration (example using Spring Security)
# spring:
#   security:
#     user:
#       name: user
#       password: password

# Additional web-specific configurations
