spring:
  application:
    name: buskart-search-web
  datasource:
    url: jdbc:postgresql://localhost:5432/Buskart   # Ensure this is your correct database URL
    username: postgres                             # Ensure the username is correct
    password: Admin                                # Ensure the password is correct
    driver-class-name: org.postgresql.Driver       # PostgreSQL driver class
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: false
  profiles:
    active: default

server:
  port: 8081

# Swagger/OpenAPI Configuration (if using Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
